### Enroll a student in a course
POST https://cse341-learning-academy.onrender.com/enrollment
Content-Type: application/json

{
  "studentId": "64d2f1bc9a7a4e001e9a1a11",
  "courseId": "64d2f1bc9a7a4e001e9a1b22"
}

###

### Drop a course
DELETE https://cse341-learning-academy.onrender.com/enrollment/64d2f1bc9a7a4e001e9a1c33

###

### Get all enrollments for a student
GET https://cse341-learning-academy.onrender.com/enrollment/student/68882f1f81a46581d5d8b760

###

### Get all students enrolled in a course
GET https://cse341-learning-academy.onrender.com/enrollment/course/64d2f1bc9a7a4e001e9a1b22

###

### Update course progress
PUT https://cse341-learning-academy.onrender.com/enrollment/68914f29b0e99c1556ead1c3/progress
Content-Type: application/json

{
  "progress": "completed"
}