### GET all instructors
GET https://cse341-learning-academy.onrender.com/instructor

### GET instructor by id
GET https://cse341-learning-academy.onrender.com/instructor/68882f9b81a46581d5d8b762

### CREATE instructor
POST https://cse341-learning-academy.onrender.com/instructor HTTP/1.1
content-type: application/json

{
  "firstName": "Juan",
  "lastName": "García",
  "email": "juan.garcia@example.com",
  "specialty": "Frontend Development"
}

### UPDATE instructor
PUT https://cse341-learning-academy.onrender.com/instructor/68882f9b81a46581d5d8b762 HTTP/1.1
content-type: application/json

{
  "firstName": "María",
  "lastName": "Pérez",
  "email": "maria.perez@example.com",
  "specialty": "Backend Development"
}

### DELETE instructor
DELETE https://cse341-learning-academy.onrender.com/instructor/688e624d3d912d87235b0d73 HTTP/1.1
